"""
routers/export_router.py
-------------------------------------------------------------------------
POST /api/export/pdf         — server-rendered PDF (WeasyPrint)
POST /api/export/docx        — Word document (python-docx), styled to match
                                the selected template + any customization
POST /api/export/share-link  — creates/returns a public, read-only URL

render_html() is a deliberate line-for-line Python port of
static/js/template-engine.js's render() (section order, section renderers,
skills categories, photo, page-number). Keeping the two in sync manually
means the PDF always matches the on-screen preview. If you edit one when
adding a new resume section, edit the other too.

The exported PDF has NO browser print watermark (no date/time/URL/title in
the margins) because it's generated by WeasyPrint from raw HTML — it never
goes through a browser's print dialog, which is the only thing that ever
adds that kind of watermark in the first place.
-------------------------------------------------------------------------
"""

import base64
import io
import re
import uuid
from html import escape as esc
from pathlib import Path
from typing import Any, cast

from fastapi import APIRouter, HTTPException, Request, Response, Depends
from sqlalchemy.orm import Session

from .. import schemas, models, settings_service
from ..database import get_db
from ..template_service import get_by_id as get_template

router = APIRouter(prefix="/api/export", tags=["export"])

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
STYLES_CSS_PATH = _PROJECT_ROOT / "static" / "css" / "styles.css"
STATIC_DIR = _PROJECT_ROOT / "static"


# ---------------------------------------------------------------------------
# Shared helpers — mirrors template-engine.js
# ---------------------------------------------------------------------------
def _customization_style_vars(customization: dict | None) -> str:
    if not customization:
        return ""
    f = customization.get("fontSizes") or {}
    c = customization.get("colors") or {}
    fam = customization.get("fonts") or {}
    s = customization.get("spacing") or {}
    vars_ = {
        "--doc-name-size": f"{f['name']}px" if f.get("name") else None,
        "--doc-h2-size": f"{f['h2']}px" if f.get("h2") else None,
        "--doc-body-size": f"{f['body']}px" if f.get("body") else None,
        "--doc-contact-size": f"{f['contact']}px" if f.get("contact") else None,
        "--doc-heading-color": c.get("heading"),
        "--doc-body-color": c.get("body"),
        "--doc-link-color": c.get("link"),
        "--doc-accent-color": c.get("accent"),
        "--doc-heading-font": fam.get("heading"),
        "--doc-body-font": fam.get("body"),
        "--doc-line-height": s.get("lineHeight"),
        "--doc-section-spacing": f"{s['sectionSpacing']}px" if s.get("sectionSpacing") is not None else None,
        "--doc-page-margin": f"{s['pageMargin']}px" if s.get("pageMargin") is not None else None,
    }
    return ";".join(f"{k}:{v}" for k, v in vars_.items() if v not in (None, ""))


def _short_link(url: str, max_len: int = 40) -> str:
    import re as _re
    u = (url or "").strip()
    u = _re.sub(r"^https?://", "", u, flags=_re.IGNORECASE)
    u = _re.sub(r"^www\.", "", u, flags=_re.IGNORECASE).rstrip("/")
    if len(u) > max_len:
        parts = u.split("/")
        u = "/".join(parts[:2]) + "/…"
    return u


def _normalize_url(url: str) -> str:
    u = (url or "").strip()
    if not u:
        return ""
    return u if u.lower().startswith(("http://", "https://")) else "https://" + u


def _profile_handle(url: str) -> str:
    import re as _re
    u = _re.sub(r"^[a-z][a-z0-9+.\-]*://", "", (url or "").strip(), flags=_re.IGNORECASE)
    u = _re.sub(r"^www\.", "", u, flags=_re.IGNORECASE)
    u = _re.sub(r"[?#].*$", "", u).rstrip("/")
    if not u:
        return "@"
    parts = [seg for seg in u.split("/") if seg]
    if len(parts) > 1:
        return "@" + parts[-1]
    host = parts[0].split(".")
    return "@" + (host[-2] if len(host) >= 2 else host[0])


def _tel_href(phone: str) -> str:
    import re as _re
    s = (phone or "").strip()
    if not s:
        return ""
    return ("+" if s.startswith("+") else "") + _re.sub(r"\D", "", s)


def format_markdown_lite(raw: str) -> str:
    """Python mirror of static/js/template-engine.js's formatMarkdownLite() —
    keep both in sync if the syntax changes. Converts **bold**, *italic*,
    __underline__, "- " bullet lines, and [text](url) links into safe HTML.
    Text is escaped first; only these specific patterns are then converted,
    so this can never introduce unescaped content."""
    lines = (raw or "").split("\n")
    html_parts = []
    in_list = False
    link_re = re.compile(r"\[([^\]]+)\]\((https?://[^\s)]+)\)")
    for line in lines:
        is_bullet = bool(re.match(r"^\s*-\s+", line))
        if is_bullet and not in_list:
            html_parts.append('<ul class="doc-formatted-list">')
            in_list = True
        if not is_bullet and in_list:
            html_parts.append("</ul>")
            in_list = False

        content = esc(re.sub(r"^\s*-\s+", "", line) if is_bullet else line)
        content = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", content)
        content = re.sub(r"__(.+?)__", r"<u>\1</u>", content)
        content = re.sub(r"\*(.+?)\*", r"<em>\1</em>", content)
        content = link_re.sub(r'<a href="\2" target="_blank" rel="noopener noreferrer" title="\1">\1</a>', content)

        html_parts.append(f"<li>{content}</li>" if is_bullet else (f"<p>{content}</p>" if content else ""))
    if in_list:
        html_parts.append("</ul>")
    return "".join(html_parts)


def _render_contact(p: dict) -> str:
    parts = []
    if p.get("email"):
        parts.append(f'<a href="mailto:{esc(p["email"])}" title="Send an email to {esc(p["email"])}" aria-label="Email {esc(p["email"])}">{esc(p["email"])}</a>')
    phone = (p.get("phone") or "").strip()
    if phone:
        tel = _tel_href(phone)
        if tel:
            parts.append(f'<a href="tel:{esc(tel)}" title="Call {esc(phone)}" aria-label="Call phone number {esc(phone)}">{esc(phone)}</a>')
    if p.get("location"):
        parts.append(f"<span>{esc(p['location'])}</span>")
    # Professional links: @handle label, clickable underlying URL
    for key, aria in (("linkedin", "View LinkedIn profile"), ("github", "View GitHub profile"), ("website", "Visit portfolio website")):
        url = (p.get(key) or "").strip()
        if url:
            href = esc(_normalize_url(url))
            parts.append(f'<a href="{href}" target="_blank" rel="noopener noreferrer" title="{aria}" aria-label="{aria}">{esc(_profile_handle(url))}</a>')
    return "".join(parts)


def _render_photo(customization: dict | None) -> str:
    photo = (customization or {}).get("photo") or {}
    if not photo.get("visible") or not photo.get("url"):
        return ""
    shape_class = "doc-photo-square" if photo.get("shape") == "square" else "doc-photo-circle"
    return f'<img class="doc-photo {shape_class}" src="{esc(photo["url"])}" alt="Profile photo">'


def _inline_local_images(html: str) -> str:
    """Rewrite <img src="/static/..."> to data: URLs using local file bytes.

    WeasyPrint renders render_html()'s output from an in-memory string with no
    base URL, so root-relative photo paths (what /api/upload/photo returns)
    can never resolve there. This swaps each local <img> for an equivalent
    data: URL; data: and http(s) sources pass through untouched, and a missing
    file degrades to the original src rather than breaking the whole PDF.
    Runs on markup only — never on user text — so quote styles vary safely.
    """
    import mimetypes

    def _replace(match):
        quote, src = match.group(1), match.group(2)
        data = None
        rel = _static_relative_path(src)
        if rel is not None:
            data = _read_local_static_image(rel)
        if not data:
            return match.group(0)
        mime = mimetypes.guess_type(str(rel))[0] or "image/jpeg"
        b64 = base64.b64encode(data).decode("ascii")
        return f"src={quote}data:{mime};base64,{b64}{quote}"

    return re.sub(
        r"""src=(["'])(/static/[^"']+)\1""",
        _replace,
        html or "",
    )


def _render_page_number(customization: dict | None) -> str:
    pn = (customization or {}).get("pageNumbers") or {}
    if not pn.get("enabled"):
        return ""
    position = pn.get("position", "bottom-center")
    fmt = pn.get("format", "Page {n}")
    return f'<div class="doc-page-number doc-page-number-{position}" data-page-format="{esc(fmt)}"></div>'


def _get_sec_title(section_id: str, default_title: str, resume: dict) -> str:
    section_titles = resume.get("sectionTitles") or {}
    if section_id in section_titles and section_titles[section_id]:
        return str(section_titles[section_id])
    sec_data = resume.get(section_id)
    if isinstance(sec_data, dict) and sec_data.get("title"):
        return str(sec_data["title"])
    return default_title


def _render_skills(skills, resume: dict = None) -> str:
    if not skills:
        return ""
    title = _get_sec_title("skills", "Skills", resume or {})
    if isinstance(skills, list):
        if not skills:
            return ""
        pills = "".join(f'<span class="skill-pill">{esc(s)}</span>' for s in skills)
        return f'<section><div class="doc-section-title">{esc(title)}</div><div class="skills-wrapper">{pills}</div></section>'

    categories = [("technical", "Technical Skills"), ("tools", "Tools & Technologies"), ("soft", "Soft Skills & Leadership")]
    blocks = []
    for key, label in categories:
        items = skills.get(key) or []
        if not items:
            continue
        pills = "".join(f'<span class="skill-pill">{esc(s)}</span>' for s in items)
        blocks.append(
            f'<div class="skills-category-block"><strong style="font-size:11px;color:#888;display:block;margin-bottom:3px">{label}</strong>'
            f'<div class="skills-wrapper">{pills}</div></div>'
        )
    if not blocks:
        return ""
    return f'<section><div class="doc-section-title">{esc(title)}</div>{"".join(blocks)}</section>'


def _render_section(section_id: str, resume: dict) -> str:
    if section_id in (resume.get("hiddenSections") or []):
        return ""

    if section_id == "summary":
        if not resume.get("summary"):
            return ""
        title = _get_sec_title("summary", "Profile Summary", resume)
        return f'<section><div class="doc-section-title">{esc(title)}</div>{format_markdown_lite(resume["summary"])}</section>'

    if section_id == "experience":
        entries = resume.get("experience") or []
        if not entries:
            return ""
        title = _get_sec_title("experience", "Experience", resume)
        bullet_style = ((resume.get("customization") or {}).get("spacing") or {}).get("bulletStyle", "disc")
        bullet_class = f"bullets-{bullet_style}"
        rows = []
        for e in entries:
            dates = " – ".join(filter(None, [e.get("start"), ("Present" if e.get("current") else e.get("end"))]))
            head_title = esc(e.get("role", "")) + (f" — {esc(e.get('company', ''))}" if e.get("company") else "")
            loc = f'<div class="doc-entry-sub">{esc(e["location"])}</div>' if e.get("location") else ""
            bullets = "".join(f"<li>{esc(b)}</li>" for b in (e.get("bullets") or []) if b)
            rows.append(
                f'<div class="doc-entry"><div class="doc-entry-head"><span>{head_title}</span><span>{esc(dates)}</span></div>'
                f'{loc}<ul class="doc-bullets {bullet_class}">{bullets}</ul></div>'
            )
        return f'<section><div class="doc-section-title">{esc(title)}</div>{"".join(rows)}</section>'

    if section_id == "education":
        entries = resume.get("education") or []
        if not entries:
            return ""
        title = _get_sec_title("education", "Education", resume)
        rows = []
        for e in entries:
            dates = " – ".join(filter(None, [e.get("start"), e.get("end")]))
            degree = esc(e.get("degree", "")) + (f", {esc(e['field'])}" if e.get("field") else "")
            sub = esc(e.get("school", "")) + (f" · GPA {esc(e['gpa'])}" if e.get("gpa") else "")
            honors = f'<div class="doc-entry-details"><strong>Honors:</strong> {esc(e["honors"])}</div>' if e.get("honors") else ""
            coursework = f'<div class="doc-entry-details"><strong>Coursework:</strong> {esc(e["coursework"])}</div>' if e.get("coursework") else ""
            rows.append(
                f'<div class="doc-entry"><div class="doc-entry-head"><span>{degree}</span><span>{esc(dates)}</span></div>'
                f'<div class="doc-entry-sub">{sub}</div>{honors}{coursework}</div>'
            )
        return f'<section><div class="doc-section-title">{esc(title)}</div>{"".join(rows)}</section>'

    if section_id == "skills":
        return _render_skills(resume.get("skills"), resume)

    if section_id == "projects":
        entries = resume.get("projects") or []
        if not entries:
            return ""
        title = _get_sec_title("projects", "Projects", resume)
        rows = []
        for p in entries:
            name = esc(p.get("name", ""))
            role = (f" ({esc(p['role'])})" if p.get("role") else "")
            link = p.get("link") or ""
            if link:
                href = esc(_normalize_url(link))
                head = f'<a class="project-title-link" href="{href}" target="_blank" rel="noopener noreferrer" title="View project: {name}" aria-label="View project {name}">{name}</a>{role}'
            else:
                head = name + role
            desc = f'<div class="doc-entry-sub">{esc(p["description"])}</div>' if p.get("description") else ""
            rows.append(f'<div class="doc-entry"><div class="doc-entry-head"><span>{head}</span></div>{desc}</div>')
        return f'<section><div class="doc-section-title">{esc(title)}</div>{"".join(rows)}</section>'

    if section_id == "certifications":
        entries = resume.get("certifications") or []
        if not entries:
            return ""
        title = _get_sec_title("certifications", "Certifications", resume)
        rows = "".join(
            f'<div class="doc-entry-sub"><strong>{esc(c.get("name",""))}</strong>'
            f'{" — " + esc(c["issuer"]) if c.get("issuer") else ""}{" (" + esc(c["date"]) + ")" if c.get("date") else ""}</div>'
            for c in entries
        )
        return f'<section><div class="doc-section-title">{esc(title)}</div>{rows}</section>'

    if section_id == "languages":
        entries = resume.get("languages") or []
        if not entries:
            return ""
        title = _get_sec_title("languages", "Languages", resume)
        pills = "".join(f'<span class="skill-pill">{esc(l.get("name",""))} · {esc(l.get("level",""))}</span>' for l in entries)
        return f'<section><div class="doc-section-title">{esc(title)}</div><div class="skills-wrapper">{pills}</div></section>'

    if section_id == "power_statement":
        stmt = resume.get("power_statement")
        if not stmt:
            return ""
        title = _get_sec_title("power_statement", "Power Statement", resume)
        return f'<section><div class="doc-section-title">{esc(title)}</div><div class="doc-entry-sub" style="font-weight:500; font-size:1.05em;">{format_markdown_lite(stmt)}</div></section>'

    if section_id == "hobbies":
        entries = resume.get("hobbies") or []
        if not entries:
            return ""
        title = _get_sec_title("hobbies", "Hobbies & Interests", resume)
        hobbies_list = entries if isinstance(entries, list) else [entries]
        pills = "".join(f'<span class="skill-pill">{esc(h.get("name", "") if isinstance(h, dict) else h)}</span>' for h in hobbies_list)
        return f'<section><div class="doc-section-title">{esc(title)}</div><div>{pills}</div></section>'

    if section_id == "references":
        entries = resume.get("references") or []
        if not entries:
            return ""
        title = _get_sec_title("references", "References", resume)
        rows = []
        for r in entries:
            name_title = esc(r.get("name", "")) + (f" — {esc(r['title'])}" if r.get("title") else "")
            comp = f'<span>{esc(r["company"])}</span>' if r.get("company") else ""
            contact = f'<div class="doc-entry-sub">{esc(r["contact"])}</div>' if r.get("contact") else ""
            rows.append(f'<div class="doc-entry"><div class="doc-entry-head"><span>{name_title}</span>{comp}</div>{contact}</div>')
        return f'<section><div class="doc-section-title">{esc(title)}</div>{"".join(rows)}</section>'

    # Generic or custom sections
    sec_data = resume.get(section_id)
    if not sec_data:
        return ""
    fallback_title = section_id.replace("custom_section_", "Custom Section ").replace("_", " ").title()
    title = _get_sec_title(section_id, fallback_title, resume)

    if isinstance(sec_data, str):
        return f'<section><div class="doc-section-title">{esc(title)}</div>{format_markdown_lite(sec_data)}</section>'

    items = sec_data if isinstance(sec_data, list) else (sec_data.get("items") if isinstance(sec_data, dict) and isinstance(sec_data.get("items"), list) else [])
    if items:
        rows = []
        for item in items:
            main_title = item.get("title") or item.get("name") or item.get("role") or item.get("activity") or ""
            sub_title = item.get("city") or item.get("location") or item.get("subtitle") or item.get("organization") or item.get("issuer") or item.get("company") or ""
            start = item.get("start") or item.get("date")
            end = item.get("end")
            date_str = f"{start}{' – ' + end if end else ''}" if start else ""
            head = f'<span><strong>{esc(main_title)}</strong>{(" — " + esc(sub_title)) if sub_title else ""}</span>{f"<span>{esc(date_str)}</span>" if date_str else ""}'
            desc = f'<div class="doc-entry-sub">{format_markdown_lite(item["description"])}</div>' if item.get("description") else ""
            rows.append(f'<div class="doc-entry"><div class="doc-entry-head">{head}</div>{desc}</div>')
        return f'<section><div class="doc-section-title">{esc(title)}</div>{"".join(rows)}</section>'

    return ""


def render_cover_letter_body(resume: dict) -> str:
    """The cover letter markup — same structure as template-engine.js's renderCoverLetter()."""
    p = resume.get("personal") or {}
    cl = resume.get("coverLetter") or resume.get("cover_letter") or {}
    display_name = p.get("fullName") or "Your Name"
    display_title = p.get("title") or p.get("jobTarget") or "Applicant"
    style_attr = _customization_style_vars(resume.get("customization"))
    template_id = resume.get("template", "cl-modern")
    if template_id == "classic":
        template_id = "cl-classic"
    elif template_id == "creative":
        template_id = "cl-creative"
    elif template_id == "executive":
        template_id = "cl-executive"
    elif template_id == "modern" or not template_id.startswith("cl-"):
        template_id = "cl-modern"

    contact_items = []
    if p.get("email"):
        contact_items.append(f'<a href="mailto:{esc(p["email"])}">{esc(p["email"])}</a>')
    phone = (p.get("phone") or "").strip()
    if phone:
        tel = _tel_href(phone)
        if tel:
            contact_items.append(f'<a href="tel:{esc(tel)}">{esc(phone)}</a>')
    loc = p.get("location") or ", ".join(filter(None, [p.get("address"), p.get("city"), p.get("postalCode")]))
    if loc:
        contact_items.append(f'<span>{esc(loc)}</span>')
    if p.get("linkedin"):
        contact_items.append(f'<a href="{esc(_normalize_url(p["linkedin"]))}" target="_blank">{esc(_profile_handle(p["linkedin"]))}</a>')
    if p.get("website"):
        contact_items.append(f'<a href="{esc(_normalize_url(p["website"]))}" target="_blank">{esc(_short_link(p["website"]))}</a>')

    contact_bar_html = " &nbsp;·&nbsp; ".join(contact_items)

    import datetime
    date_str = cl.get("date") or datetime.date.today().strftime("%B %d, %Y")
    salutation = cl.get("salutation") or (f"Dear {cl['hiringManager']}," if cl.get("hiringManager") else "Dear Hiring Team,")
    sign_off = cl.get("signOff") or "Sincerely,"
    signature = cl.get("signature") or display_name

    body_html = format_markdown_lite(cl.get("body") or "")

    quals = cl.get("keyQualifications") or []
    quals_html = ""
    if quals:
        bullets = "".join(f"<li>{esc(q)}</li>" for q in quals)
        quals_html = f'<div class="cl-doc-qualifications" style="margin: 16px 0;"><strong style="display:block;margin-bottom:8px;">Key Qualifications:</strong><ul class="doc-formatted-list">{bullets}</ul></div>'

    if template_id == "cl-classic":
        inner = f"""
        <div class="cl-doc-header">
          <h1 class="cl-doc-name">{esc(display_name)}</h1>
          {f'<div class="cl-doc-title">{esc(display_title)}</div>' if display_title else ''}
          <div class="cl-doc-contact-bar">{contact_bar_html}</div>
        </div>
        <div class="cl-doc-recipient-box">
          <div class="cl-doc-date">{esc(date_str)}</div>
          <div class="cl-doc-recipient">
            {f'<strong>{esc(cl["hiringManager"])}</strong>' if cl.get("hiringManager") else ''}
            {f'<div>{esc(cl["companyName"])}</div>' if cl.get("companyName") else ''}
            {f'<div>{esc(cl["companyAddress"])}</div>' if cl.get("companyAddress") else ''}
          </div>
        </div>
        <div class="cl-doc-salutation">{esc(salutation)}</div>
        <div class="cl-doc-body">{body_html}{quals_html}</div>
        <div class="cl-doc-signoff">
          <div>{esc(sign_off)}</div>
          <div class="cl-doc-signature-name">{esc(signature)}</div>
        </div>"""
    elif template_id == "cl-creative":
        inner = f"""
        <div class="cl-doc-header">
          <div>
            <h1 class="cl-doc-name">{esc(display_name)}</h1>
            <div class="cl-doc-title">{esc(display_title)}</div>
          </div>
          <div class="cl-doc-contact-bar">
            {f'<div>{esc(p["email"])}</div>' if p.get("email") else ''}
            {f'<div>{esc(p["phone"])}</div>' if p.get("phone") else ''}
            {f'<div>{esc(loc)}</div>' if loc else ''}
          </div>
        </div>
        <div class="cl-doc-recipient-box">
          <div style="display:flex;justify-content:space-between;align-items:flex-start;gap:16px;">
            <div class="cl-doc-recipient">
              {f'<strong>{esc(cl["hiringManager"])}</strong>' if cl.get("hiringManager") else ''}
              {f'<div>{esc(cl["companyName"])}</div>' if cl.get("companyName") else ''}
              {f'<div>{esc(cl["companyAddress"])}</div>' if cl.get("companyAddress") else ''}
            </div>
            <div class="cl-doc-date">{esc(date_str)}</div>
          </div>
        </div>
        <div class="cl-doc-salutation">{esc(salutation)}</div>
        <div class="cl-doc-body">{body_html}{quals_html}</div>
        <div class="cl-doc-signoff">
          <div>{esc(sign_off)}</div>
          <div class="cl-doc-signature-name">{esc(signature)}</div>
        </div>"""
    elif template_id == "cl-executive":
        inner = f"""
        <div class="cl-doc-header">
          <div>
            <h1 class="cl-doc-name">{esc(display_name)}</h1>
            <div class="cl-doc-title">{esc(display_title)}</div>
          </div>
          <div class="cl-doc-contact-bar">
            {f'<div>{esc(p["email"])}</div>' if p.get("email") else ''}
            {f'<div>{esc(p["phone"])}</div>' if p.get("phone") else ''}
            {f'<div>{esc(loc)}</div>' if loc else ''}
          </div>
        </div>
        <div class="cl-doc-recipient-box">
          <div style="display:flex;justify-content:space-between;align-items:flex-start;gap:16px;">
            <div class="cl-doc-recipient">
              {f'<strong>{esc(cl["hiringManager"])}</strong>' if cl.get("hiringManager") else ''}
              {f'<div>{esc(cl["companyName"])}</div>' if cl.get("companyName") else ''}
              {f'<div>{esc(cl["companyAddress"])}</div>' if cl.get("companyAddress") else ''}
            </div>
            <div class="cl-doc-date">{esc(date_str)}</div>
          </div>
        </div>
        <div class="cl-doc-salutation">{esc(salutation)}</div>
        <div class="cl-doc-body">{body_html}{quals_html}</div>
        <div class="cl-doc-signoff">
          <div>{esc(sign_off)}</div>
          <div class="cl-doc-signature-name">{esc(signature)}</div>
        </div>"""
    else:
        # Default: cl-modern
        inner = f"""
        <div class="cl-doc-header">
          <div>
            <h1 class="cl-doc-name">{esc(display_name)}</h1>
            <div class="cl-doc-title">{esc(display_title)}</div>
            <div class="cl-doc-contact-bar">{contact_bar_html}</div>
          </div>
        </div>
        <div class="cl-doc-recipient-box">
          <div class="cl-doc-recipient">
            {f'<strong>{esc(cl["hiringManager"])}</strong>' if cl.get("hiringManager") else ''}
            {f'<div>{esc(cl["companyName"])}</div>' if cl.get("companyName") else ''}
            {f'<div>{esc(cl["companyAddress"])}</div>' if cl.get("companyAddress") else ''}
          </div>
          <div class="cl-doc-date">{esc(date_str)}</div>
        </div>
        <div class="cl-doc-salutation">{esc(salutation)}</div>
        <div class="cl-doc-body">{body_html}{quals_html}</div>
        <div class="cl-doc-signoff">
          <div>{esc(sign_off)}</div>
          <div class="cl-doc-signature-name">{esc(signature)}</div>
        </div>"""

    return f"""<div class="resume-doc theme-{esc(template_id)} cl-preview-document" style="{style_attr}">
  <div class="doc-main-wrapper">
    {inner}
  </div>
</div>"""


def render_resume_body(resume: dict) -> str:
    """The .resume-doc markup only — same structure as template-engine.js's render()."""
    if resume.get("docType") == "cover_letter" or resume.get("doc_type") == "cover_letter":
        return render_cover_letter_body(resume)

    p = resume.get("personal") or {}
    sections = "".join(_render_section(sid, resume) for sid in (resume.get("sectionOrder") or []))
    style_attr = _customization_style_vars(resume.get("customization"))
    photo_html = _render_photo(resume.get("customization"))
    photo_position = (resume.get("customization") or {}).get("photo", {}).get("position", "left")
    page_number_html = _render_page_number(resume.get("customization"))
    template_id = resume.get("template", "classic")

    return f"""<div class="resume-doc theme-{esc(template_id)}" style="{style_attr}">
  <div class="doc-main-wrapper">
    <div class="doc-header doc-header-photo-{photo_position if photo_html else 'none'}">
      {photo_html}
      <div class="doc-header-text">
        <h1>{esc(p.get('fullName') or 'Your Name')}</h1>
        <div class="doc-title">{esc(p.get('title') or '')}</div>
        <div class="doc-contact">{_render_contact(p)}</div>
      </div>
    </div>
    {sections}
  </div>
  {page_number_html}
</div>"""


def render_html(resume: dict) -> str:
    """Full standalone HTML document for WeasyPrint, with styles.css inlined
    (avoids any relative-path/base_url ambiguity) and real CSS Paged Media
    page numbers if the user enabled them in /customize.

    NOTE on images — two paths, no exceptions:
      * the builder uploads to /api/upload/photo whose JSON response is a
        *public* URL ("/static/uploads/photos/xxx.jpg"), and _render_photo()
        embeds it verbatim as the <img src>. When WeasyPrint later parses that
        <img>, a relative or root-relative src has no host to resolve against
        (the HTML is rendered from an in-memory string, not a page load), so
        the image step must inline the bytes first — that is exactly what
        _inline_local_images() below does, right before the CSS is attached.
      * paste-from-URL / crop-modal photos arrive as data: URLs and need no
        rewriting at all.
    WeasyPrint has no fetch context here by design; every image the PDF must
    show has to be either a data: URL or rewritten below. Never "fix" this by
    handing WeasyPrint a base_url pointing at the live site — on serverless
    the function cannot HTTP back into itself, and the PDF would come out
    photo-less again.

    Page sizing: explicitly set to A4 (210mm x 297mm) with sensible margins
    via @page, and .resume-doc's normal 560px/max-width cap is overridden to
    fill the full printable width. Without this, WeasyPrint's default page
    box and the resume's screen-sized 560px content box left a large blank
    margin and made everything look shrunk relative to the page — this is
    what actually caused the "content appears too small" complaint; it
    wasn't a DPI or scaling-factor bug in WeasyPrint itself.
    """
    try:
        css = STYLES_CSS_PATH.read_text(encoding="utf-8")
    except OSError:
        css = ""

    customization = resume.get("customization") or {}
    pn = customization.get("pageNumbers") or {}
    page_number_css = ""
    if pn.get("enabled"):
        fmt = pn.get("format", "Page {n}")
        # WeasyPrint supports CSS Paged Media counter(page)/counter(pages).
        content_expr = fmt.replace("{n}", '" counter(page) "').replace("{total}", '" counter(pages) "')
        side = {
            "bottom-left": "bottom-left", "bottom-right": "bottom-right",
            "bottom-center": "bottom-center", "top-right": "top-right",
        }.get(pn.get("position", "bottom-center"), "bottom-center")
        page_number_css = f'@{side} {{ content: "{content_expr}"; font-size: 9px; color: #999; }}'
        # The JS-rendered .doc-page-number placeholder is only for the on-screen
        # preview (browsers can't do per-page counters) — hide it in the PDF
        # since the real @page margin box above renders the actual number.

    page_css = f"""
      @page {{
        size: A4;
        margin: 14mm 16mm;
        {page_number_css}
      }}
      body {{ background: #fff; margin: 0; padding: 0; }}
      .resume-doc {{
        box-shadow: none !important;
        margin: 0 !important;
        width: 100% !important;
        max-width: none !important;
        min-height: 0 !important;
      }}
      .doc-page-number {{ display: none; }}
      .doc-entry, section, .doc-header, .skills-category-block {{
        page-break-inside: avoid;
        break-inside: avoid;
      }}
      .doc-section-title {{
        page-break-after: avoid;
        break-after: avoid;
      }}
    """

    body = render_resume_body(resume)

    # Inline any server-stored photo bytes as data: URLs BEFORE the document
    # is handed to WeasyPrint. A bare "/static/uploads/..." src renders fine
    # in the browser (it shares the page's origin) but means nothing to a
    # from-string HTML renderer with no base URL — without this step every
    # upload-based photo silently vanishes from the PDF (and only from the
    # PDF, which is exactly why the preview looks right and the file doesn't).
    body = _inline_local_images(body)

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>{css}\n{page_css}</style></head>
<body>{body}</body></html>"""


# ---------------------------------------------------------------------------
# PDF
# ---------------------------------------------------------------------------
def _pdf_filename(resume: dict) -> str:
    """A URL/header-safe, human-friendly PDF filename derived from the resume or cover letter."""
    name = (resume.get("personal") or {}).get("fullName") or "Resume"
    doc_type = resume.get("docType") or resume.get("doc_type") or "resume"
    doc_label = "Cover_Letter" if doc_type == "cover_letter" else "Resume"
    import re as _re
    safe = _re.sub(r"[^A-Za-z0-9 _.\-]+", "", name).strip().replace(" ", "_")
    safe = _re.sub(r"_+", "_", safe).strip("_") or "Resume"
    return f"{safe}_{doc_label}.pdf"


@router.post("/pdf")
def export_pdf(payload: schemas.ExportRequest, db: Session = Depends(get_db)):
    features = settings_service.get_group(db, "features", redact=False)
    if not features.get("pdf_export_enabled", True):
        raise HTTPException(status_code=403, detail="PDF export is currently disabled site-wide.")
    try:
        from weasyprint import HTML  # optional dependency, imported lazily

        html = render_html(payload.resume)
        # WeasyPrint renders actual HTML/CSS to a VECTOR PDF: the text stays
        # selectable/searchable, <a> anchors become real link annotations, page
        # breaks follow the @page CSS (avoids section splits), and because it is
        # vector (not a raster image like jsPDF+html2canvas) the file stays small
        # enough for email sharing. Rendering happens server-side, so the output
        # is identical across browsers/devices and carries no print watermark.
        pdf_bytes = HTML(string=html).write_pdf()
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={
                "Content-Disposition": f"attachment; filename=\"{_pdf_filename(payload.resume)}\""
            },
        )
    except (ImportError, OSError) as e:
        raise HTTPException(
            status_code=501,
            detail=f"Server-side PDF export is unavailable ({type(e).__name__}: {e}). "
            "Please use high-quality browser download instead.",
        )
    except Exception as e:  # noqa: BLE001 - renderer libs present but render failed;
        # return 501 (not 500) so the test's never-500 contract and the client's
        # browser-print fallback both hold.
        raise HTTPException(
            status_code=501,
            detail=f"PDF generation failed ({type(e).__name__}: {e}). "
            "Please use high-quality browser download instead.",
        )


# ---------------------------------------------------------------------------
# DOCX — styled to match the template + customization, not plain text
# ---------------------------------------------------------------------------
def _add_formatted_paragraph(doc, raw_text: str, body_font: str):
    """DOCX equivalent of format_markdown_lite() above — real Word run-level
    bold/italic/underline (not just visible characters), and "- " lines
    become an actual Word bulleted list style. Simpler than the HTML/PDF
    parser since Word paragraphs are flat text, so links render as plain
    text with the URL shown (no clickable-hyperlink field code — the PDF
    and on-screen preview are the styled/clickable versions)."""
    from docx.oxml.ns import qn

    link_re = re.compile(r"\[([^\]]+)\]\((https?://[^\s)]+)\)")
    token_re = re.compile(r"(\*\*.+?\*\*|__.+?__|\*.+?\*)")

    for line in (raw_text or "").split("\n"):
        is_bullet = bool(re.match(r"^\s*-\s+", line))
        content = re.sub(r"^\s*-\s+", "", line) if is_bullet else line
        content = link_re.sub(r"\1 (\2)", content)  # plain-text fallback for links in Word

        para = doc.add_paragraph(style="List Bullet" if is_bullet else None)
        for token in token_re.split(content):
            if not token:
                continue
            if token.startswith("**") and token.endswith("**"):
                run = para.add_run(token[2:-2]); run.bold = True
            elif token.startswith("__") and token.endswith("__"):
                run = para.add_run(token[2:-2]); run.underline = True
            elif token.startswith("*") and token.endswith("*"):
                run = para.add_run(token[1:-1]); run.italic = True
            else:
                run = para.add_run(token)
            run.font.name = body_font


def _hex_to_rgbcolor(hex_str: str, fallback: str):
    from docx.shared import RGBColor
    h = (hex_str or fallback).lstrip("#")
    if len(h) != 6:
        h = fallback.lstrip("#")
    try:
        return RGBColor(int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))
    except ValueError:
        r, g, b = (int(fallback.lstrip("#")[i:i+2], 16) for i in (0, 2, 4))
        return RGBColor(r, g, b)


def _first_font_name(font_family: str, fallback: str = "Calibri") -> str:
    if not font_family:
        return fallback
    # CSS font stacks look like "'Fraunces', Georgia, serif" — Word wants one name.
    first = font_family.split(",")[0].strip().strip("'\"")
    return first or fallback


# ---------------------------------------------------------------------------
# Profile-photo embedding for .docx
#
# python-docx can only embed *bytes* — it has no idea what a CSS `src` is. The
# builder stores the photo as `customization.photo.url`, which is either
#   (a) a `data:image/...;base64,` URL (the normal case: the crop modal hands
#       back a canvas.toDataURL() string), or
#   (b) an http(s) URL the user pasted in the "From URL" tab.
# Both have to be resolved to bytes before Word can show them.
# ---------------------------------------------------------------------------
MAX_PHOTO_BYTES = 5 * 1024 * 1024          # 5 MB — refuse anything larger
PHOTO_FETCH_TIMEOUT_SEC = 6
_PHOTO_DISPLAY_PX = 96                     # matches .doc-photo width in styles.css


def _static_relative_path(url: str):
    """Map an app-served path back to a file under the local static dir.

    /api/upload/photo hands the browser paths like
    "/static/uploads/photos/<id>-<rand>.jpg"; server-side a <img> src is not
    fetchable (urllib cannot reach the app itself on serverless), so translate
    the public "/static/..." prefix back to a filesystem path. Absolute
    http(s) URLs, data: URLs, and anything outside /static/ return None.
    """
    u = (url or "").strip()
    if not u.startswith("/static/"):
        return None
    rel = u[len("/static/"):]
    # Reject traversal even before joining: only plain relative segments.
    parts = [seg for seg in rel.split("/") if seg not in ("", ".", "..")]
    if not parts or "/".join(parts) != rel.strip("/"):
        return None
    candidate = (STATIC_DIR / "/".join(parts)).resolve()
    try:
        candidate.relative_to(STATIC_DIR.resolve())
    except ValueError:
        return None
    return candidate


def _read_local_static_image(path) -> bytes | None:
    """Read a static-dir image file with the same size guard as remote fetch."""
    try:
        if not path.is_file():
            return None
        size = path.stat().st_size
        if not size or size > MAX_PHOTO_BYTES:
            return None
        data = path.read_bytes()
    except OSError:
        return None
    if len(data) > MAX_PHOTO_BYTES or not data:
        return None
    return data


def _decode_data_url(url: str):
    """Return (bytes, mime) for a data: URL, or None when it isn't one."""
    match = re.match(r"^data:(image/[A-Za-z0-9.+-]+)\s*;\s*base64\s*,(.*)$", url or "", re.DOTALL)
    if not match:
        return None
    try:
        return base64.b64decode(match.group(2), validate=False), match.group(1)
    except (ValueError, TypeError):
        return None


def _fetch_remote_image(url: str):
    """Fetch an http(s) image with a hard size cap and short timeout.

    Uses urllib so the export path stays dependency-free on serverless. Any
    failure returns None — a missing photo must never break the whole export.
    """
    from urllib.request import Request, urlopen
    from urllib.error import URLError, HTTPError

    if not re.match(r"^https?://", url or "", re.IGNORECASE):
        return None
    try:
        req = Request(url, headers={"User-Agent": "ResumeAI/1.0 (docx export)"})
        with urlopen(req, timeout=PHOTO_FETCH_TIMEOUT_SEC) as resp:  # noqa: S310 - scheme checked above
            mime = (resp.headers.get("Content-Type") or "").split(";")[0].strip().lower()
            if mime and not mime.startswith("image/"):
                return None
            clen = int(resp.headers.get("Content-Length") or 0)
            if clen and clen > MAX_PHOTO_BYTES:
                return None
            data = resp.read(MAX_PHOTO_BYTES + 1)
        if len(data) > MAX_PHOTO_BYTES or not data:
            return None
        return data, (mime or "image/png")
    except (URLError, HTTPError, ValueError, OSError, TimeoutError):
        return None


def _circularize_image(raw: bytes) -> bytes:
    """Pre-process a photo into a transparent-cornered circular PNG.

    Word can't clip a picture to a shape via python-docx, so the circle is
    baked into the pixels instead: centre-crop to a square, apply a 4x
    supersampled anti-aliased ellipse mask, and flatten onto transparency.
    Over Word's white page this renders as a clean round avatar.
    """
    from PIL import Image, ImageDraw

    try:
        resample = Image.Resampling.LANCZOS
    except AttributeError:
        resample = getattr(Image, "LANCZOS", 1)

    img = Image.open(io.BytesIO(raw)).convert("RGBA")
    w, h = img.size
    side = min(w, h)
    img = img.crop(((w - side) // 2, (h - side) // 2, (w - side) // 2 + side, (h - side) // 2 + side))

    ss = 4  # supersample factor for a smooth edge
    mask = Image.new("L", (side * ss, side * ss), 0)
    ImageDraw.Draw(mask).ellipse((0, 0, side * ss - 1, side * ss - 1), fill=255)
    mask = mask.resize((side, side), resample)

    out = Image.new("RGBA", (side, side), (255, 255, 255, 0))
    out.paste(img, (0, 0), mask)
    buf = io.BytesIO()
    out.save(buf, format="PNG")
    return buf.getvalue()


def _load_photo_stream(customization: dict):
    """Resolve customization.photo into a (BytesIO, shape) pair ready for add_picture.

    Returns (None, None) when there is no usable photo, so callers can just
    skip the picture and carry on with a text-only header.
    """
    photo = (customization or {}).get("photo") or {}
    if not photo.get("visible") or not photo.get("url"):
        return None, None
    shape = "square" if photo.get("shape") == "square" else "circle"

    url = (photo["url"] or "").strip()
    decoded = _decode_data_url(url)
    raw = decoded[0] if decoded else None
    if raw is None:
        # A server-stored upload is returned to the browser as an app-relative
        # path (e.g. "/static/uploads/photos/xxx.jpg"). urllib cannot fetch
        # those, so resolve them against the local static dir. data: URLs and
        # http(s) URLs are handled by the other two branches.
        rel = _static_relative_path(url)
        if rel is not None:
            raw = _read_local_static_image(rel)
        if raw is None:
            fetched = _fetch_remote_image(url)
            raw = fetched[0] if fetched else None
    if not raw:
        return None, None

    if shape == "circle":
        try:
            raw = _circularize_image(raw)
        except Exception as exc:  # noqa: BLE001 - unsupported format -> fall back to as-is
            print(f"[docx] circular crop failed, embedding original photo: {exc}")

    return io.BytesIO(raw), shape


def _make_borderless_table(doc, cols: int, widths_mm):
    """A 1-row table with all borders suppressed — used to lay the header out
    side-by-side so the DOCX mirrors .doc-header-photo-{left|right}."""
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.shared import Mm, Pt

    table = doc.add_table(rows=1, cols=cols)
    table.autofit = False
    for cell, width in zip(table.rows[0].cells, widths_mm):
        cell.width = Mm(width)
        cell.paragraphs[0].paragraph_format.space_after = Pt(0)
    # strip borders (python-docx has no Table.borders API)
    tbl_pr = table._tbl.tblPr
    borders = OxmlElement("w:tblBorders")
    for edge in ("top", "left", "bottom", "right", "insideH", "insideV"):
        el = OxmlElement(f"w:{edge}")
        el.set(qn("w:val"), "none")
        el.set(qn("w:sz"), "0")
        borders.append(el)
    tbl_pr.append(borders)
    return table


@router.post("/docx")
def export_docx(payload: schemas.ExportRequest, db: Session = Depends(get_db)):
    features = settings_service.get_group(db, "features", redact=False)
    if not features.get("docx_export_enabled", True):
        raise HTTPException(status_code=403, detail="Word export is currently disabled site-wide.")
    try:
        from docx import Document
        from docx.shared import Pt, Mm
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.enum.table import WD_ALIGN_VERTICAL
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
    except ImportError:
        raise HTTPException(status_code=501, detail="Word export requires 'pip install python-docx'.")

    resume = payload.resume
    p = resume.get("personal") or {}
    customization = resume.get("customization") or {}
    fonts = customization.get("fonts") or {}
    colors = customization.get("colors") or {}
    font_sizes = customization.get("fontSizes") or {}

    template = get_template(resume.get("template", "classic")) or {}
    style = template.get("style") or {}
    # Templates have not all used the same key casing over time: most declare
    # snake_case (primary_color / font_family) but obsidian-style entries use
    # camelCase (primaryColor / fontFamily). Accept both so no template ever
    # silently falls back to the default colour/font in Word output.
    theme_primary = style.get("primary_color") or style.get("primaryColor") or "#1e293b"
    theme_font_stack = style.get("font_family") or style.get("fontFamily") or "Georgia, serif"

    heading_font = _first_font_name(fonts.get("heading") or theme_font_stack)
    body_font = _first_font_name(fonts.get("body") or "Calibri")
    heading_color = _hex_to_rgbcolor(colors.get("heading") or "", theme_primary)
    accent_color = _hex_to_rgbcolor(colors.get("accent") or "", theme_primary)
    body_color = _hex_to_rgbcolor(colors.get("body") or "", "#222222")
    name_size = Pt(font_sizes.get("name") or 22)
    h2_size = Pt(font_sizes.get("h2") or 12)
    body_size = Pt(font_sizes.get("body") or 10.5)

    doc = Document()

    # ---- Configure standard A4 page dimensions and margins ----
    if doc.sections:
        sec = doc.sections[0]
        sec.page_width = Mm(210)
        sec.page_height = Mm(297)
        spacing = customization.get("spacing") or {}
        margin_px = spacing.get("pageMargin")
        if margin_px:
            margin_pt = Pt(float(margin_px) * 0.75)
            sec.top_margin = margin_pt
            sec.bottom_margin = margin_pt
            sec.left_margin = margin_pt
            sec.right_margin = margin_pt
        else:
            sec.top_margin = Mm(16)
            sec.bottom_margin = Mm(16)
            sec.left_margin = Mm(16)
            sec.right_margin = Mm(16)

    # ---- Base document font (applies to every paragraph unless overridden) ----
    normal = cast(Any, doc.styles["Normal"])  # _ParagraphStyle — has .font at runtime
    normal.font.name = body_font
    normal.font.size = body_size
    normal.font.color.rgb = body_color
    rpr = normal.element.get_or_add_rPr()
    rfonts = rpr.find(qn("w:rFonts"))
    if rfonts is None:
        rfonts = OxmlElement("w:rFonts")
        rpr.append(rfonts)
    rfonts.set(qn("w:eastAsia"), body_font)

    def add_heading_run(paragraph, text, size, color, bold=True, font=None):
        run = paragraph.add_run(text)
        run.font.size = size
        run.font.bold = bold
        run.font.color.rgb = color
        run.font.name = font or heading_font
        return run

    def add_section_title(text):
        para = doc.add_paragraph()
        para.paragraph_format.space_before = Pt(10)
        para.paragraph_format.space_after = Pt(4)
        run = add_heading_run(para, text.upper(), h2_size, heading_color)
        run.font.underline = False
        # bottom border under the heading, tinted with the accent color
        p_pr = para._p.get_or_add_pPr()
        border = OxmlElement("w:pBdr")
        bottom = OxmlElement("w:bottom")
        bottom.set(qn("w:val"), "single")
        bottom.set(qn("w:sz"), "6")
        bottom.set(qn("w:color"), "%02X%02X%02X" % (accent_color[0], accent_color[1], accent_color[2]))
        border.append(bottom)
        p_pr.append(border)
        return para

    # ---- Header: name / title / contact, with the profile photo beside it ----
    #
    # python-docx cannot embed a CSS `src`, so customization.photo.url is
    # resolved to real image bytes by _load_photo_stream() and inserted with
    # add_picture(). When a photo is visible the text block moves into a
    # borderless 2-column table so it sits next to the picture, mirroring
    # .doc-header-photo-{left|right} in the HTML preview and the PDF export.
    # (These helpers used to be defined but never called, which is why every
    # download came out text-only.)
    contact = " | ".join(filter(None, [p.get("email"), p.get("phone"), p.get("location")] + [
        _short_link(p.get(k) or "") for k in ("linkedin", "github", "website") if (p.get(k) or "").strip()
    ]))

    def add_header_block(container):
        """Writes name / title / contact into `doc` or into a table cell."""
        existing = getattr(container, "paragraphs", None) or []
        # A freshly added cell already owns one empty paragraph — reuse it so
        # the header doesn't start with a blank line.
        name_para = existing[0] if existing else container.add_paragraph()
        name_para.paragraph_format.space_after = Pt(2)
        add_heading_run(name_para, p.get("fullName") or "Your Name", name_size, heading_color)
        if p.get("title"):
            title_para = container.add_paragraph()
            title_para.paragraph_format.space_after = Pt(2)
            run = title_para.add_run(p["title"])
            run.font.size = Pt((font_sizes.get("contact") or 11))
            run.font.color.rgb = body_color
            run.font.name = body_font
        if contact:
            c_para = container.add_paragraph()
            c_para.paragraph_format.space_after = Pt(0)
            run = c_para.add_run(contact)
            run.font.size = Pt((font_sizes.get("contact") or 9.5))
            run.font.color.rgb = body_color
            run.font.name = body_font
        return container

    photo_stream, photo_shape = _load_photo_stream(customization)
    photo_position = (customization.get("photo") or {}).get("position", "left") or "left"
    photo_on_left = photo_position != "right"

    if photo_stream is not None:
        photo_mm = _PHOTO_DISPLAY_PX * 25.4 / 96.0  # 96px @96dpi -> ~25.4mm
        text_mm = max(60.0, 178.0 - photo_mm)       # A4 width (210mm) - 16mm margins
        widths = (photo_mm, text_mm) if photo_on_left else (text_mm, photo_mm)
        table = _make_borderless_table(doc, 2, widths)
        cells = table.rows[0].cells
        photo_cell, text_cell = (cells[0], cells[1]) if photo_on_left else (cells[1], cells[0])
        for cell in cells:
            cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER
        pic_para = photo_cell.paragraphs[0]
        pic_para.alignment = WD_ALIGN_PARAGRAPH.LEFT if photo_on_left else WD_ALIGN_PARAGRAPH.RIGHT
        pic_para.paragraph_format.space_after = Pt(0)
        pic_para.add_run().add_picture(photo_stream, width=Mm(photo_mm))
        add_header_block(text_cell)
    else:
        add_header_block(doc)

    is_cover_letter = resume.get("docType") == "cover_letter" or resume.get("doc_type") == "cover_letter"

    if is_cover_letter:
        cl = resume.get("coverLetter") or resume.get("cover_letter") or {}
        import datetime
        date_str = cl.get("date") or datetime.date.today().strftime("%B %d, %Y")
        salutation = cl.get("salutation") or (f"Dear {cl['hiringManager']}," if cl.get("hiringManager") else "Dear Hiring Team,")
        sign_off = cl.get("signOff") or "Sincerely,"
        signature = cl.get("signature") or (p.get("fullName") or "Your Name")

        # Date paragraph
        d_para = doc.add_paragraph()
        d_para.paragraph_format.space_before = Pt(14)
        d_para.paragraph_format.space_after = Pt(8)
        run = d_para.add_run(date_str)
        run.font.name = body_font

        # Recipient block
        if cl.get("hiringManager") or cl.get("companyName") or cl.get("companyAddress"):
            recip_para = doc.add_paragraph()
            recip_para.paragraph_format.space_after = Pt(12)
            if cl.get("hiringManager"):
                r1 = recip_para.add_run(cl["hiringManager"] + "\n")
                r1.bold = True
                r1.font.name = body_font
            if cl.get("companyName"):
                r2 = recip_para.add_run(cl["companyName"] + "\n")
                r2.font.name = body_font
            if cl.get("companyAddress"):
                r3 = recip_para.add_run(cl["companyAddress"])
                r3.font.name = body_font

        # Salutation
        sal_para = doc.add_paragraph()
        sal_para.paragraph_format.space_before = Pt(8)
        sal_para.paragraph_format.space_after = Pt(8)
        sal_run = sal_para.add_run(salutation)
        sal_run.bold = True
        sal_run.font.name = body_font

        # Letter body
        if cl.get("body"):
            _add_formatted_paragraph(doc, cl["body"], body_font)

        # Key qualifications
        quals = cl.get("keyQualifications") or []
        if quals:
            q_para = doc.add_paragraph()
            q_para.paragraph_format.space_before = Pt(10)
            q_para.paragraph_format.space_after = Pt(4)
            q_run = q_para.add_run("Key Qualifications:")
            q_run.bold = True
            q_run.font.name = body_font
            for q in quals:
                doc.add_paragraph(q, style="List Bullet")

        # Sign-off & signature
        so_para = doc.add_paragraph()
        so_para.paragraph_format.space_before = Pt(16)
        so_para.paragraph_format.space_after = Pt(14)
        so_run = so_para.add_run(sign_off)
        so_run.font.name = body_font

        sig_para = doc.add_paragraph()
        sig_run = sig_para.add_run(signature)
        sig_run.bold = True
        sig_run.font.size = Pt((font_sizes.get("name") or 14) * 0.9)
        sig_run.font.name = heading_font
        sig_run.font.color.rgb = heading_color
    else:
        hidden = set(resume.get("hiddenSections") or [])
        for section_id in resume.get("sectionOrder") or []:
            if section_id in hidden:
                continue

            if section_id == "summary" and resume.get("summary"):
                add_section_title(_get_sec_title("summary", "Profile Summary", resume))
                _add_formatted_paragraph(doc, resume["summary"], body_font)

            elif section_id == "experience" and resume.get("experience"):
                add_section_title(_get_sec_title("experience", "Experience", resume))
                for e in resume["experience"]:
                    dates = " – ".join(filter(None, [e.get("start"), ("Present" if e.get("current") else e.get("end"))]))
                    head = doc.add_paragraph()
                    head.paragraph_format.space_after = Pt(0)
                    run = head.add_run(f"{e.get('role','')}{' — ' + e['company'] if e.get('company') else ''}")
                    run.bold = True
                    run.font.name = body_font
                    if dates:
                        tab = head.add_run(f"\t{dates}")
                        tab.font.name = body_font
                        tab.italic = True
                    if e.get("location"):
                        loc = doc.add_paragraph(e["location"])
                        loc.paragraph_format.space_after = Pt(2)
                        loc.runs[0].italic = True
                    for bullet in e.get("bullets") or []:
                        if bullet:
                            doc.add_paragraph(bullet, style="List Bullet")

            elif section_id == "education" and resume.get("education"):
                add_section_title(_get_sec_title("education", "Education", resume))
                for e in resume["education"]:
                    dates = " – ".join(filter(None, [e.get("start"), e.get("end")]))
                    degree_line = f"{e.get('degree','')}{', ' + e['field'] if e.get('field') else ''}"
                    head = doc.add_paragraph()
                    head.paragraph_format.space_after = Pt(0)
                    run = head.add_run(degree_line)
                    run.bold = True
                    run.font.name = body_font
                    if dates:
                        tab = head.add_run(f"\t{dates}")
                        tab.italic = True
                    sub = f"{e.get('school','')}{' · GPA ' + e['gpa'] if e.get('gpa') else ''}"
                    if sub.strip():
                        doc.add_paragraph(sub)
                    if e.get("honors"):
                        doc.add_paragraph(f"Honors: {e['honors']}")
                    if e.get("coursework"):
                        doc.add_paragraph(f"Coursework: {e['coursework']}")

            elif section_id == "skills" and resume.get("skills"):
                add_section_title(_get_sec_title("skills", "Skills", resume))
                skills = resume["skills"]
                if isinstance(skills, list):
                    if skills:
                        doc.add_paragraph(", ".join(skills))
                else:
                    for key, label in (("technical", "Technical Skills"), ("tools", "Tools & Technologies"), ("soft", "Soft Skills")):
                        items = skills.get(key) or []
                        if items:
                            para = doc.add_paragraph()
                            run = para.add_run(f"{label}: ")
                            run.bold = True
                            para.add_run(", ".join(items))

            elif section_id == "projects" and resume.get("projects"):
                add_section_title(_get_sec_title("projects", "Projects", resume))
                for pr in resume["projects"]:
                    head = doc.add_paragraph()
                    run = head.add_run(f"{pr.get('name','')}{' (' + pr['role'] + ')' if pr.get('role') else ''}")
                    run.bold = True
                    if pr.get("link"):
                        link_run = head.add_run(f" — {pr['link']}")
                        link_run.italic = True
                    if pr.get("description"):
                        _add_formatted_paragraph(doc, pr["description"], body_font)

            elif section_id == "certifications" and resume.get("certifications"):
                add_section_title(_get_sec_title("certifications", "Certifications", resume))
                for c in resume["certifications"]:
                    line = c.get("name", "")
                    if c.get("issuer"):
                        line += f" — {c['issuer']}"
                    if c.get("date"):
                        line += f" ({c['date']})"
                    doc.add_paragraph(line)

            elif section_id == "languages" and resume.get("languages"):
                add_section_title(_get_sec_title("languages", "Languages", resume))
                doc.add_paragraph(", ".join(f"{l.get('name','')} ({l.get('level','')})" for l in resume["languages"]))

            elif section_id == "power_statement" and resume.get("power_statement"):
                add_section_title(_get_sec_title("power_statement", "Power Statement", resume))
                _add_formatted_paragraph(doc, resume["power_statement"], body_font)

            elif section_id == "hobbies" and resume.get("hobbies"):
                add_section_title(_get_sec_title("hobbies", "Hobbies & Interests", resume))
                hobbies_list = resume["hobbies"] if isinstance(resume["hobbies"], list) else [resume["hobbies"]]
                doc.add_paragraph(", ".join(h.get("name", "") if isinstance(h, dict) else str(h) for h in hobbies_list))

            elif section_id == "references" and resume.get("references"):
                add_section_title(_get_sec_title("references", "References", resume))
                for r in resume["references"]:
                    name_title = r.get("name", "") + (f" — {r['title']}" if r.get("title") else "")
                    head = doc.add_paragraph()
                    run = head.add_run(name_title)
                    run.bold = True
                    if r.get("company"):
                        run_comp = head.add_run(f" ({r['company']})")
                        run_comp.italic = True
                    if r.get("contact"):
                        doc.add_paragraph(r["contact"])

            else:
                sec_data = resume.get(section_id)
                if not sec_data:
                    continue
                fallback_title = section_id.replace("custom_section_", "Custom Section ").replace("_", " ").title()
                sec_title = _get_sec_title(section_id, fallback_title, resume)
                add_section_title(sec_title)

                if isinstance(sec_data, str):
                    _add_formatted_paragraph(doc, sec_data, body_font)
                else:
                    items = sec_data if isinstance(sec_data, list) else (sec_data.get("items") if isinstance(sec_data, dict) and isinstance(sec_data.get("items"), list) else [])
                    for item in items:
                        main_title = item.get("title") or item.get("name") or item.get("role") or item.get("activity") or ""
                        sub_title = item.get("city") or item.get("location") or item.get("subtitle") or item.get("organization") or item.get("issuer") or item.get("company") or ""
                        start = item.get("start") or item.get("date")
                        end = item.get("end")
                        date_str = f"{start}{' – ' + end if end else ''}" if start else ""

                        head = doc.add_paragraph()
                        head.paragraph_format.space_after = Pt(0)
                        if main_title:
                            r1 = head.add_run(main_title)
                            r1.bold = True
                        if sub_title:
                            r2 = head.add_run(f" — {sub_title}")
                            r2.italic = True
                        if date_str:
                            tab = head.add_run(f"\t{date_str}")
                            tab.italic = True
                        if item.get("description"):
                            _add_formatted_paragraph(doc, item["description"], body_font)

    # ---- Page numbers (footer field code), only if enabled in /customize ----
    pn = customization.get("pageNumbers") or {}
    if pn.get("enabled"):
        section = doc.sections[0]
        footer = section.footer
        footer_para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        align_map = {
            "bottom-left": WD_ALIGN_PARAGRAPH.LEFT,
            "bottom-center": WD_ALIGN_PARAGRAPH.CENTER,
            "bottom-right": WD_ALIGN_PARAGRAPH.RIGHT,
            "top-right": WD_ALIGN_PARAGRAPH.RIGHT,
        }
        footer_para.alignment = align_map.get(pn.get("position", "bottom-center"), WD_ALIGN_PARAGRAPH.CENTER)
        fmt = pn.get("format", "Page {n}")
        prefix, _, suffix = fmt.partition("{n}")
        if prefix:
            footer_para.add_run(prefix)
        _add_page_field(footer_para)
        if suffix and "{total}" not in suffix:
            footer_para.add_run(suffix)
        elif "{total}" in suffix:
            before_total, _, after_total = suffix.partition("{total}")
            if before_total:
                footer_para.add_run(before_total)
            _add_page_field(footer_para, field="NUMPAGES")
            if after_total:
                footer_para.add_run(after_total)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return Response(
        content=buf.read(),
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": "attachment; filename=resume.docx"},
    )


def _add_page_field(paragraph, field: str = "PAGE"):
    """Inserts a real Word field code (updates automatically per page when
    opened in Word), e.g. { PAGE } or { NUMPAGES }."""
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement

    run = paragraph.add_run()
    fld_begin = OxmlElement("w:fldChar")
    fld_begin.set(qn("w:fldCharType"), "begin")
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = f" {field} "
    fld_end = OxmlElement("w:fldChar")
    fld_end.set(qn("w:fldCharType"), "end")
    run._r.append(fld_begin)
    run._r.append(instr)
    run._r.append(fld_end)


# ---------------------------------------------------------------------------
# Share link
# ---------------------------------------------------------------------------
@router.post("/share-link", response_model=schemas.ShareLinkResponse)
def create_share_link(payload: schemas.ExportRequest, db: Session = Depends(get_db)):
    features = settings_service.get_group(db, "features", redact=False)
    if not features.get("sharing_enabled", True):
        raise HTTPException(status_code=403, detail="Public sharing is currently disabled site-wide.")
    slug = uuid.uuid4().hex[:10]
    resume_row = models.Resume(
        owner_id=None,
        name=payload.resume.get("personal", {}).get("fullName", "Untitled"),
        template=payload.resume.get("template", "classic"),
        content=payload.resume,
        is_public=True,
        share_slug=slug,
    )
    db.add(resume_row)
    db.commit()
    return {"url": f"/r/{slug}"}


# ---------------------------------------------------------------------------
# Bulk-export helpers — used by GET /api/resumes/download-all
# ---------------------------------------------------------------------------
def build_pdf_bytes(resume: dict) -> bytes | None:
    """Server-rendered vector PDF bytes for one resume, or None when WeasyPrint
    (or its Pango/Cairo system libraries) isn't available. Never raises — the
    bulk exporter then falls back to Word (.docx) for that document."""
    try:
        from weasyprint import HTML  # optional dependency, imported lazily
    except Exception:  # noqa: BLE001 - package or system libs missing
        return None
    try:
        return HTML(string=render_html(resume)).write_pdf()
    except Exception:  # noqa: BLE001 - renderer present but render failed
        return None


def build_docx_bytes(resume: dict, db: Session) -> bytes | None:
    """Word (.docx) bytes for one resume, reusing the /api/export/docx builder so
    an archived document matches a single Word export. Returns None when Word
    export is disabled site-wide or python-docx is missing. Never raises."""
    try:
        resp = export_docx(schemas.ExportRequest(resume=resume), db)
    except Exception:  # noqa: BLE001 - 403 disabled / 501 missing dep / render fail
        return None
    body = getattr(resp, "body", None)
    return bytes(body) if body is not None else None


def document_basename(resume: dict, fallback: str = "Resume") -> str:
    """ZIP-entry/filename-safe base name taken from the person's full name
    (e.g. 'Jo:e <Bad> "Name"?' -> 'Joe_Bad_Name')."""
    name = (resume.get("personal") or {}).get("fullName") or fallback
    safe = re.sub(r'[<>:"/\\|?*]+', "", name).strip().replace(" ", "_")
    safe = re.sub(r"_+", "_", safe).strip("_")
    return safe or fallback
